version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build docs
      - run: npm run docs:build

  deploy:
    executor: node-executor
    filters:
      branches:
        only:
          - master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies

      # deploy docs
      - run: echo hello
