version: 2

defaults: &defaults
  docker:
    - image: circleci/node:lts

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build docs
      - run: npm run docs:build

      - save_cache:
          paths:
            - docs
          key: docs

  deploy:
    <<: *defaults
    filters:
      branches:
        only:
          - master

    steps:
      - checkout

      # Download cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies

      # Download cached docs
      - restore_cache:
          keys:
            - docs

      # deploy docs
      - run: npm run docs:deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
